#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           2
bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#076678"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add Alacritty --one-shot desktop=^2 && alacritty &
bspc rule --add Chromium --one-shot desktop=^1 && chromium &
# bspc rule --add Polybar layer=above
bspc rule --add Zathura state=tiled
bspc desktop -f '^1'

# Launch polybar
# $HOME/.config/polybar/launch.sh
