#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add kitty --one-shot desktop=^2 && kitty --single-instance &
bspc rule --add Chromium --one-shot desktop=^1 && chromium &
bspc desktop -f '^1'
