#!/usr/bin/env bash
kitty @ set-colors --all --configured ~/.config/kitty/dark
sed -i 's/set background=light/set background=dark/' "$HOME"/.vim/vimrc
sed -i 's/set background=light/set background=dark/' "$HOME"/.vim/kitty.vim
