#!/usr/bin/env bash
kitty @ set-colors --all --configured ~/.config/kitty/light
sed -i 's/set background=dark/set background=light/' "$HOME"/.config/nvim/init.vim
sed -i 's/set background=dark/set background=light/' "$HOME"/.config/nvim/kitty.vim
