#!/usr/bin/env bash
kitty @ set-colors --all --configured ~/.config/kitty/light
sed -i 's/set background=dark/set background=light/' ~/.vim/vimrc
sed -i 's/set background=dark/set background=light/' ~/.vim/vimrcs
