#!/bin/bash

NODE_CURRENT=$(bspc query -N -n focused)
bspc node $NODE_CURRENT -i --flag hidden=on
# bspc node $NODE_CURRENT --focus
bspc rule --add "*" --one-shot focused=on state=locked \
    node=$(bspc query -N -d -n '.leaf.!window')
"$@" >/dev/null 2>&1 &
WATCH=$(bspc subscribe -c 1 node_add)
NODE_NEW=${WATCH##* }
# echo $NODE_NEW
# bspc node -s $NODE_CURRENT
while read EVENT
do
    [ "${EVENT##* }" = "$NODE_NEW" ] && break
done < <(bspc subscribe node_remove)
# bspc node $NODE_NEW -i --flag hidden=on &&
bspc node $NODE_CURRENT --flag hidden=off --focus
