#! /usr/bin/env bash

raw_volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
shopt -s extglob
volume_with_dot=${raw_volume##Volume: ?(0)}
volume=${volume_with_dot/./}
echo "$volume" > "$HOME"/.local/bin/xob_volume_fifo
